baseurl: "https://nicofiorini.xyz"
url : "https://nicofiorini.xyz"
languageCode: "en-us"
title: "N!co"
theme: "hugo-xmin"
# googleAnalytics: ""
disqusShortname: ""
# ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

  # note: "/note/:year/:month/:day/:slug/"
permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Categories
      url: "categories/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3
    - name: About
      url: "about/"
      weight: 4
    - name: rss 
      url: "index.xml"
      weight: 5

params:
  description: "Nico Fiorini's Blog"
  footer: "[Nico Fiorini](https://nicofiorini.xyz) | [Github](https://github.com/flowibbia) | [Instagram](https://instagram.com/nico.fiorini)"

# non so a che serviva
# markup:
#   goldmark:
#     renderer:
#       unsafe: true
